### ISSUE TITLE
Stop logging SPARQL query

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sparql-loader#85]
This results in the logging of a huge amount of data.

![screen shot 2019-01-15 at 9 11 03 am](https://user-images.githubusercontent.com/588335/51185624-ae08e600-18a5-11e9-9bbb-a5ce538c281a.png)

**Comment by aaron-collier** [comment]
Yeah, aware of this and using it to debug. will have this turned off sometime today.

**Comment by aaron-collier** [comment]
Actually, I'm wondering if there is more work to do in the logging. Most of the current logging is from assessment and debugging. It hasn't been the most helpful outside of that, so I may rework it a bit and do a related PR.
